# This is based on https://github.com/gitpod-io/template-haskell

image:
  file: .gitpod.Dockerfile
tasks:
  - init:
      stack build
vscode:
  extensions:
    - haskell.haskell
    - justusadam.language-haskell
    - anwar.papyrus-pdf
