name: smcdel
version: 1.3.0
synopsis: Symbolic Model Checking for Dynamic Epistemic Logic
description: See README.md and SMCDEL.pdf for references and documentation.
maintainer: Malvin Gattinger <malvin@w4eg.eu>
license: GPL-2
github: jrclogic/SMCDEL
category: Logic

ghc-options: -Wall

extra-source-files:
  - README.md
  - CHANGELOG.md
  - stack.yaml
  - package.yaml
  - static/ace.js
  - static/mode-smcdel.js
  - static/index.html
  - static/viz-lite.js
  - Examples/CherylsBirthday.smcdel.txt
  - Examples/DiningCryptographers.smcdel.txt
  - Examples/MuddyChildren.smcdel.txt
  - Examples/DrinkingLogicians.smcdel.txt

build-tools:
  - alex
  - happy

library:
  source-dirs:
    - src
  dependencies:
    - base >= 4.8 && < 5
    - array
    - containers
    - cudd == 0.1.0.0
    - directory
    - graphviz
    - HasCacBDD >= 0.2.0.0 && < 0.3
    - process
    - QuickCheck
    - tagged
    - temporary
    - text
    - time
    - decision-diagrams

executables:
  smcdel:
    source-dirs: exec
    main: smcdel.hs
    other-modules: Paths_smcdel
    dependencies:
      - base >= 4.8 && < 5
      - ansi-terminal
      - directory
      - filepath
      - process
      - smcdel
  smcdel-web:
    source-dirs: exec
    main: smcdel-web.hs
    ghc-options: -threaded
    dependencies:
      - base >= 4.8 && < 5
      - deepseq
      - file-embed
      - scotty
      - HasCacBDD >= 0.2.0.0 && < 0.3
      - js-jquery >= 3
      - smcdel
      - template-haskell
      - text
      - warp

tests:
  examples:
    main: test/Examples.hs
    ghc-options: -with-rtsopts=-M8G
    dependencies:
      - base >= 4.8 && < 5
      - HasCacBDD
      - hspec
      - QuickCheck
      - smcdel
  translations:
    main: test/Translations.hs
    ghc-options: -with-rtsopts=-M8G
    dependencies:
      - base >= 4.8 && < 5
      - hspec
      - smcdel
  k:
    main: test/K.hs
    ghc-options: -with-rtsopts=-M8G
    dependencies:
      - base >= 4.8 && < 5
      - containers
      - hspec
      - QuickCheck
      - smcdel
  web:
    main: test/Web.hs
    ghc-options: -with-rtsopts=-M8G
    dependencies:
      - base
      - process
      - sandwich
      - sandwich-webdriver
      - text
      - webdriver
  CUDD:
    main: test/CUDD.hs
    ghc-options: -with-rtsopts=-M8G
    dependencies:
      - base >= 4.8 && < 5
      - containers
      - HasCacBDD
      - hspec
      - QuickCheck
      - smcdel

benchmarks:
  bench-diningcrypto:
    source-dirs: bench
    main: diningcrypto.hs
    dependencies:
      - base >= 4.8 && < 5
      - smcdel
      - time

  bench-sumandproduct:
    source-dirs: bench
    main: sumandproduct.hs
    dependencies:
      - base >= 4.8 && < 5
      - criterion
      - smcdel
      - time

  bench-muddychildren:
    source-dirs: bench
    main: muddychildren.hs
    dependencies:
      - base >= 4.8 && < 5
      - bytestring
      - cassava
      - criterion
      - directory
      - scientific
      - smcdel
      - split
      - vector

  sizes-muddychildren:
    source-dirs:     sizeExperiments
    main:            muddychildren.hs
    dependencies:
      - base >= 4.8 && < 5
      - bytestring
      - cassava
      - criterion
      - directory
      - scientific
      - smcdel
      - split
      - vector

  sizes-diningcryptographers:
    source-dirs:     sizeExperiments
    main:            diningcryptographers.hs
    dependencies:
      - base >= 4.8 && < 5
      - bytestring
      - cassava
      - criterion
      - directory
      - scientific
      - smcdel
      - split
      - vector

  sizes-sumandproduct:
    source-dirs:     sizeExperiments
    main:            sumandproduct.hs
    dependencies:
      - base >= 4.8 && < 5
      - bytestring
      - cassava
      - criterion
      - directory
      - scientific
      - smcdel
      - split
      - vector
